### ISSUE TITLE
[NEW]: Document search totalCount

### ISSUE THREAD

**Issue by kostasb** [xataio/mdx-docs#52] opened 2023-07-26 15:11 UTC
### Priority

Low

### Description

Once the SDK is updated to support totalCount, ref. https://github.com/xataio/client-ts/issues/1081, the typescript client search docs https://xata.io/docs/typescript-client/search should be updated to reference the new `totalCount` field in all response objects and examples.

### How will this impact users?

Document the new field totalCount (breaking change in SDK).

### Context

The backend now provides a totalCount field in search responses.

**Comment by joan-ing** [comment] 2024-01-23 11:58
Closing. Duplicate of [169](https://github.com/xataio/docs/issues/169)

**Closed by joan-ing** 2024-01-23 11:58 UTC
Labels: new content
